# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 561b08726bb9f0157e49044c4ec488450a64ebf05aaa62fb01133ae0e92568d8c182f1a4e1e327e047c006d8dba335da8c3dcdb0a93596bcfc97c776d8fc1422

test:
  secret_key_base: 60a8253075d5f36e9b76a7fe9737b4368df62c0de15aebed90a00a31123c0d4f03e9ad638b780beb24f407b84a4886ad2a072acddd45ebc28a7398cdf9bf07b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
